### ISSUE TITLE
RFC: non-crud operations: Is ember-ajax working for us?

### ISSUE THREAD

**Issue by pnw** [mediasuitenz/tech-stack#13]
# Questions:

Is ember-ajax working for us?
## Current ember-ajax paradigm:
- ember ajax + putting actions on models
- handling forms in the client that don't have an ember model to work on
- manual error handling when you don't have a model

**Comment by anotheredward** [comment]
On the loopback side, I've started to tend towards hitting a CRUD endpoint with a query parameter rather than remote methods. Otherwise you end up re-implementing a whole bunch of stuff that is out of the box with CRUD methods.

**Comment by pnw** [comment]
> On the loopback side, I've started to tend towards hitting a CRUD endpoint with a query parameter rather than remote methods. Otherwise you end up re-implementing a whole bunch of stuff that is out of the box with CRUD methods.

I don't understand

**Comment by anotheredward** [comment]
I have misunderstood this PR :)

**Comment by anotheredward** [comment]
Did we make any headway on this issue @pnw ?

**Comment by pnw** [comment]
I don't think so, but I've been pretty happy with ember-concurrency.

**Comment by anotheredward** [comment]
Is that pretty much covered by: https://www.mediasuite.co.nz/blog/day-life-ember-concurrency-task/ @pnw ? Or is taht something that deserves another blog article?

**Comment by pnw** [comment]
Well that's a totally different topic really. That blog post is about ember-concurrency, and this issue is about ember-ajax 😛

**Comment by anotheredward** [comment]
Seems good, also consider:  https://github.com/ember-cli/ember-fetch
This can be covered in the "Commonly use Ember Plugins" blog article.
