### ISSUE TITLE
RFC: Ember-concurrency best practices

### ISSUE THREAD

**Issue by pnw** [mediasuitenz/tech-stack#14]
Talking points
- What do we get from ember-concurrency
- How/where to wrap actions properly
- Things to avoid

**Comment by digitalsadhu** [comment]
Any chance you can flesh out some thoughts here @pnw ahead of Thursday's session?

**Comment by pnw** [comment]
Yeah I will @digitalsadhu

**Comment by anotheredward** [comment]
This is a really interesting issue to me, I just saw this post:
https://emberway.io/ember-concurrency-the-solution-to-so-many-problems-you-never-knew-you-had-cce6d7731ba9#.5rdxdj3wa

Which makes ember concurrency look sweeeeet.

**Comment by anotheredward** [comment]
This resulted in a sweet blog post: https://www.mediasuite.co.nz/blog/day-life-ember-concurrency-task/
