### ISSUE TITLE
RFC: Node Version Pinning/Upgrades and Patching

### ISSUE THREAD

**Issue by anotheredward** [mediasuitenz/tech-stack#15]
There has been a lot of discussion around whether we should pin our npm modules to specific versions or leave the ^ that allows patch version upgrades, and is added by default when you npm --save.
The conclusion at our last tech-stack meeting was to use --save-exact and not include the ^, but our package.json files don't really reflect this.

Pinning (saving exact versions)
Pros:
- Not vulnerable to security issues that can come as patches
- Local machine will have same libraries are server
- Fewer Breakages, as not all projects follow semver

Cons:
- Miss out on security upgrades and minor bugfixes

I feel like the Con of security patches is part of a bigger problem of not having a solid patching policy for our applications.
@tfentonz is working on one from the node version down to the OS, but Npm packages, Bower packages and other libraries still seem squarely in our court, especially due to the testing required to update.

**Comment by anotheredward** [comment]
Related #9

**Comment by JonForest** [comment]
If it helps at all, I wrote this to help pin a version for the package.json
https://gist.github.com/JonForest/2f878c379aedb7385803201191ec5cef

**Comment by digitalsadhu** [comment]
Can we really consider this an RFC without a description? ;)

**Comment by digitalsadhu** [comment]
I have a couple thoughts. 

1. option is to use shrink wrap to lock down versions. 
2. Is to consider using greenkeeper. It's pure awesome but it costs money. Green keeper watches npm projects and when a new version of something is published it checks to see if your project uses it and if so sends you a PR with the new version. This is great if you have good test coverage. It helps you keep oversight on what is changing and why.

**Comment by pnw** [comment]
@digitalsadhu poor mans version of greenkeeper: invoke something like (npm-check)[https://www.npmjs.com/package/npm-check] in a post-something git hook.

Re: RFC:

Automatically applying patch updates means that we trust each and every package author on npm that they strictly follow semantic versioning. That's a huge stretch, considering that we have some 70+ dependencies in myworksites alone. 

I've already had two separate issues with myworksites that were caused by @boredsteve having a different patch version of some package than me, wasting a lot of time.

**Comment by anotheredward** [comment]
Pinning does solve an actual problem we have.
I had this problem with ACC Roadsafe yesterday, someone had put `*` as the version number in a bower package, completely broke the application.

**Comment by anotheredward** [comment]
It's looking like we're all agreed on pinning / --save-exact.

Possible steps forward:
- Pin all version numbers in existing software, in both bower and npm config?
- Work out how to manage patches/security issues

Greenkeeper sounds good @digitalsadhu , I'm a little worried about the overhead, and also the effect on projects without adequate testing. Thoughts?

**Comment by JonForest** [comment]
I'm very keen on Greenkeeper.  If it stops one 'wtf' moment a month it pays for itself very quickly.

**Comment by anotheredward** [comment]
lockfiles, --save-exact and removing the wobbly flags inside package.json files has fixed the majority of this problem :).
