### ISSUE TITLE
Mismatch between functional programming and Ember

### ISSUE THREAD

**Issue by anotheredward** [mediasuitenz/tech-stack#16]
Ramda + Promises is pretty amazing, but things start to fall apart when Ember Objects get involved. Thoughts @ewen @ebuckley @pnw ?

**Comment by ebuckley** [comment]
Ramda extended knows how to work with a lot of ember objects, but yes, I still feel the pain.

Couple ideas off the top of my head.

1. Extend support for ramda when working with ember objects
2. Socialize the ramda-extended library at mediasuite
3. Create our own functional utility for working with Ember
4. Drop FP/pipe-madness with ember
5. Drop ember-data

**Comment by ebuckley** [comment]
Shall we close this in favor of the more complete discussion in #17 ?
