### ISSUE TITLE
RFC: Default "Definition of Done"

### ISSUE THREAD

**Issue by anotheredward** [mediasuitenz/tech-stack#23]
We've been asked by Kerry to come up with a default definition of done, which can then be reviewed by Abi.

**Comment by digitalsadhu** [comment]
We have a definition of done for My Worksites.

See: https://docs.google.com/document/d/1l5Hc1h9UR_7sZFWPiRBjWUPh8efyw0NOmrJj2U5m5og/edit#

**Comment by anotheredward** [comment]
Sweet, once that's been run by Abi, we can use that, or at least make people aware it exists.

**Comment by anotheredward** [comment]
This is a per-project decision, but the MWS one is a good default :)

**Comment by matt-in-a-hat** [comment]
Should this exemplar link be added to one of the documents of this repo?

**Comment by anotheredward** [comment]
Sure, I'll put it on the readme page
