### ISSUE TITLE
RFC: Where do we record fixes for little gotchas in our stack?

### ISSUE THREAD

**Issue by JonForest** [mediasuitenz/tech-stack#26]
During development we all come across little gaps in our tech stack where things don't work as we expect.  We bang our head against for a couple of days and eventually come up with an often pretty creative solution.

What is the best mechanism for distributing this knowledge?  The #Ember and #Loopback channels on Slack, or tech stack documentation, or something else?  How do we make it such that people can identify problems and fixes?

For example, My Worksites has got a neat little fix for stopping database errors when sending relationships back with the json-api message causes Loopback to attempt nulling of foreign key fields.  We ended up over-riding the `serializeHasMany` function in the application serializer.  It's about 2 lines of code, but took a good five hours to understand the bug and fix.  It's likely other projects will run into this.  How can we share these little insights?

**Comment by digitalsadhu** [comment]
This tech stack repo is maturing nicely thanks to some top curation from the likes of @anotheredward etc. so perhaps this is the right place? 

I guess the main problem then is one of discoverability?

**Comment by anotheredward** [comment]
I wrote a private google document called "Useful PRs" here: https://docs.google.com/spreadsheets/d/1f9dpFBNGibCu_AxNiXnEmdR-zyVkupppchXjZ2mdTrg/edit#gid=0

It is for this exact purpose.
I wanted it to be easy to add things, and the PRs it references are often private,  so I chose google docs over github.
The items on the list might make also good blog posts.

**Comment by anotheredward** [comment]
@digitalsadhu My idea on discoverability was that we can send people to this document to look at reference implementations of what they might be about to work on.

A good example is worth 1000 lines of documentation and all the good jazz.

**Comment by JonForest** [comment]
I think that spreadsheet is a great starting point @anotheredward .  I think we can take it a step forward and have reference implementations for things like:
- How we send emails (I note that My Worksites and Leapfrog did it differently)
- How we implement permissions on Ember and Loopback
- How we produce PDFs
- How we handle, resize, etc. images
- File-uploads and storage
- Lots of map things (which I don't understand, but would like to)

To be a good reference implementation, I think it should have comments coming out the wazoo.

**Comment by matt-in-a-hat** [comment]
I like this idea, but I think in forms of discoverability our best bet might just be this repo.

Does anyone see why we can't have descriptions and links to examples from our private repo files within this public repo? As long as we don't go into detail about the project, just the problem/solution and a link to the example PR or files?

I feel like it will require some good organisation to aid discoverability. Lewis, Steve and I started [a geospatial document](https://github.com/mediasuitenz/tech-stack/pull/30) for all things GIS and mapping. But if it gets too large we can split it into separate files, perhaps in a folder. And it would be good if these files referenced each other, e.g. info about doing postgis stuff in loopback could be in the loopback doc OR the geospatial doc, but put a comment in the other linking back.

Also if you think of something you'd like some documentation/examples on then add it here as a request, and if you know someone knows about it @ tag them.

**Comment by anotheredward** [comment]
Honestly @matt-in-a-hat , It's probably not a bad idea to just make this repro private and keep things here. We're starting to discuss some more sensitive stuff, so it would be a good idea to make it disappear.

**Comment by anotheredward** [comment]
I feel like the Tech-stack and the Useful PRs spreadsheet haven't worked for us, @ebuckley and I will be discussing what we could do about this/if we should do anything :).
