### ISSUE TITLE
RFC: Map stuff & spatial queries

### ISSUE THREAD

**Issue by boredsteve** [mediasuitenz/tech-stack#29]
## Description

Quite a number of our projects involves spatial querying (postGIS) and map rendering, e.g. Cruisey, Roadsafe, Detours etc etc. I think @JonForest mentioned that he'll like to know more, and I thought we should have some way of sharing tools and best practices as well.

**Comment by matt-in-a-hat** [comment]
Everyone can contribute to [this document](https://github.com/mediasuitenz/tech-stack/pull/30) with any knowledge they have on geospatial stuff and mapping etc.

**Comment by anotheredward** [comment]
@boredsteve If you have spare time, I'd love to sit down with you and work on this document: https://github.com/mediasuitenz/tech-stack/pull/30
I've learned lots from you in the past couple of weeks and it'd be good to record it.
