### ISSUE TITLE
RFC: The move to Node 6 LTS

### ISSUE THREAD

**Issue by digitalsadhu** [mediasuitenz/tech-stack#31]
## Description

Node 6 is scheduled to go into LTS within a month. This RFC is to discuss the approach we should take in regards to existing projects and new projects. Node 6 brings with it 92% support for ES6 up from 52% support in Node 4 as well as speed and boot time improvements.
## Proposed approach
1. New projects start on node 6, pretty much anything from now on since by the time they go into production node 6 will almost certainly be the newest LTS version
2. Existing projects to be updated case by case (depending on budget, need etc)
3. If an existing project is to be updated:
   1. Update node first without updating npm. This should in most cases be a net win. It should take almost no time to do and has a very low likelyhood of anything breaking
   2.  Update npm to npm 3 if possible. There are definite cases where updating npm is likely to cause pain (eg. my worksites)

**Comment by anotheredward** [comment]
Sounds excellent, the improved debugging info alone makes Node 6 a big step up :)

Will need to consider projects case-by-case, eg: 
- Leapfrog probably doesn't have the budget
- MDC apps that are installed on-site are scary to change

**Comment by pnw** [comment]
Relevant: 

[Breaking changes v4 -> v5](https://github.com/nodejs/node/wiki/Breaking-changes-between-v4-and-v5)
[Breaking changes v5 -> v6](https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6)

**Comment by anotheredward** [comment]
I feel like we came to a solid conclusion that all new apps will be on the latest sensible version of Node (probably LTS), but older apps will need to remain on older versions for compatibility reasons.
